-- Seed: Preguntas para Observación de Clase (45 reactivos, secciones A-H)
INSERT INTO instrumento_preguntas (instrumento, seccion, orden, texto) VALUES
('observacion','A',1,'Expone, organiza, desarrolla y vincula los contenidos en forma clara.'),
('observacion','A',2,'Relaciona los contenidos con situaciones reales o casos prácticos del entorno profesional.'),
('observacion','A',3,'Adapta los contenidos a los diversos estilos y necesidades de los estudiantes.'),
('observacion','A',4,'Explica conceptos complejos utilizando analogías, ejemplos claros y lenguaje accesible.'),
('observacion','A',5,'Clarifica términos técnicos o especializados según el nivel académico del grupo.'),
('observacion','A',6,'Facilita la apropiación del conocimiento mediante explicaciones estructuradas.'),
('observacion','A',7,'Promueve el razonamiento crítico y la resolución de problemas durante la clase.'),
('observacion','B',8,'Organiza espacios de reflexión antes, durante y después de las actividades.'),
('observacion','B',9,'Orienta a los estudiantes para que identifiquen sus fortalezas y áreas de oportunidad.'),
('observacion','B',10,'Incluye actividades en clase que promueven el aprendizaje autónomo.'),
('observacion','B',11,'Propone ejercicios para promover la metacognición.'),
('observacion','B',12,'Propone nuevas estrategias para mejorar los resultados obtenidos.'),
('observacion','B',13,'Favorece la transferencia de conocimientos a nuevas situaciones o contextos.'),
('observacion','B',14,'Promueve la formulación de preguntas y el pensamiento reflexivo en el aula.'),
('observacion','B',15,'Invita a los estudiantes a seleccionar estrategias de estudio.'),
('observacion','B',16,'Integra momentos de análisis sobre los errores como oportunidades de mejora.'),
('observacion','C',17,'Se comunica con un lenguaje oral y escrito apropiado y de respeto.'),
('observacion','C',18,'Se comunica con un lenguaje no verbal (corporal) apropiado y de respeto.'),
('observacion','C',19,'Comunica los propósitos, procedimientos y resultados esperados.'),
('observacion','C',20,'Diseña actividades que desarrollen la expresión escrita y oral de los estudiantes.'),
('observacion','D',21,'Procura relaciones empáticas y de respeto dentro de la praxis docente.'),
('observacion','D',22,'Proporciona igualdad de oportunidades de participación.'),
('observacion','D',23,'Promueve compromiso y solidaridad entre los estudiantes.'),
('observacion','D',24,'Establece un clima de relaciones interpersonales respetuosas y empáticas.'),
('observacion','E',25,'Organiza los objetivos y contenidos de manera coherente con el modelo TUP.'),
('observacion','E',26,'Implementa diversas estrategias para inducir el aprendizaje significativo.'),
('observacion','E',27,'Considera saberes previos, intereses y experiencias de sus estudiantes.'),
('observacion','E',28,'Genera oportunidades de desarrollo del pensamiento crítico y creativo.'),
('observacion','E',29,'Motiva al aprendizaje, la indagación y la búsqueda de conocimiento.'),
('observacion','E',30,'Integra recursos tecnológicos, didácticos y materiales complementarios.'),
('observacion','E',31,'Ofrece retroalimentación oportuna, pertinente y cálida a sus estudiantes.'),
('observacion','F',32,'Genera un ambiente propicio para el aprendizaje basado en confianza y respeto.'),
('observacion','F',33,'Identifica las fortalezas de sus estudiantes, las destaca y ofrece espacios.'),
('observacion','G',34,'Diseña tareas integradoras de proyectos utilizando las NTIC.'),
('observacion','G',35,'Promueve el empoderamiento y participación del estudiante en el uso de NTIC.'),
('observacion','G',36,'Muestra dominio en el uso de la tecnología como recurso para la enseñanza.'),
('observacion','G',37,'Aplica métodos y técnicas pertinentes a la didáctica de su campo.'),
('observacion','G',38,'Identifica estrategias de enseñanza y dificultades recurrentes.'),
('observacion','G',39,'Promueve el uso responsable, ético y seguro de las tecnologías.'),
('observacion','G',40,'Genera situaciones de aprendizaje adecuadas a los niveles de desarrollo.'),
('observacion','H',41,'Inicia puntualmente su sesión.'),
('observacion','H',42,'Entrega en tiempo y forma la planeación docente correspondiente.'),
('observacion','H',43,'Desarrolla el tema correspondiente a la semana o unidad establecida.'),
('observacion','H',44,'Registra la asistencia, evaluaciones y avances en medios institucionales.'),
('observacion','H',45,'Concluye su sesión en el tiempo señalado.')
ON CONFLICT (instrumento, orden) DO NOTHING;

-- Coordinación Académica (15 reactivos, secciones A-E)
INSERT INTO instrumento_preguntas (instrumento, seccion, orden, texto) VALUES
('coordinacion','A',1,'Cumplimiento del programa, planeación y avance académico.'),
('coordinacion','A',2,'Organización y conducción de sesiones (presenciales, virtuales o ejecutivas).'),
('coordinacion','A',3,'Uso y disponibilidad de materiales didácticos o recursos en plataforma.'),
('coordinacion','B',4,'Entrega de calificaciones en tiempo y forma.'),
('coordinacion','B',5,'Puntualidad, asistencia y cumplimiento administrativo.'),
('coordinacion','B',6,'Uso adecuado de plataformas institucionales (Moodle, Saeko, sistemas).'),
('coordinacion','C',7,'Comunicación clara, oportuna y profesional con estudiantes y coordinación.'),
('coordinacion','C',8,'Trabajo colaborativo con docentes y áreas institucionales.'),
('coordinacion','C',9,'Participación en reuniones, actividades y procesos institucionales.'),
('coordinacion','D',10,'Implementación de estrategias didácticas innovadoras.'),
('coordinacion','D',11,'Participación en procesos de capacitación o actualización docente.'),
('coordinacion','D',12,'Aplicación de mejoras en su práctica docente.'),
('coordinacion','E',13,'Cumplimiento de normatividad institucional.'),
('coordinacion','E',14,'Trato respetuoso, ético y profesional.'),
('coordinacion','E',15,'Representación institucional adecuada en entornos presenciales o digitales.')
ON CONFLICT (instrumento, orden) DO NOTHING;

-- Planeación Docente (4 criterios)
INSERT INTO instrumento_preguntas (instrumento, seccion, orden, texto) VALUES
('planeacion',NULL,1,'Alineación Curricular — Coherencia con el plan de estudios y perfil de egreso.'),
('planeacion',NULL,2,'Secuencia Didáctica — Estructura lógica de las actividades de aprendizaje.'),
('planeacion',NULL,3,'Recursos y Materiales (NTIC) — Uso de tecnología y materiales didácticos.'),
('planeacion',NULL,4,'Sistemas de Evaluación — Instrumentos y criterios de evaluación claros.')
ON CONFLICT (instrumento, orden) DO NOTHING;
